"""Rough AI-content likelihood via a single ungrounded Gemini pass.
LLM-based AI detection is unreliable — this is an indicator, NOT a verdict."""
from __future__ import annotations

from typing import Any, Dict

from facts_grounding import ungrounded_generate
from utils1 import extract_review_json

_PROMPT = """Estimate the probability that the following TEXT was generated by an AI model.
Consider signals like uniform sentence rhythm, generic phrasing, lack of specific voice,
and over-smooth transitions. Be calibrated; human writing can look polished too.

Return ONLY JSON between the markers:
BEGIN_JSON
{"likelihood": <integer 0-100>, "reasoning": "<one or two short sentences>"}
END_JSON

TEXT:
<<<
{script}
>>>
"""


def _band(likelihood: int) -> str:
    if likelihood > 66:
        return "high"
    if likelihood >= 34:
        return "medium"
    return "low"


def _generate(prompt: str) -> str:
    return ungrounded_generate(prompt, temperature=0.0)


def _gemini_ai_detection(text: str) -> Dict[str, Any]:
    """Free heuristic estimate via a single ungrounded Gemini pass (unreliable indicator)."""
    prompt = _PROMPT.replace("{script}", text or "")
    try:
        raw = _generate(prompt)
        data = extract_review_json(raw) or {}
    except Exception:
        data = {}
    try:
        likelihood = int(round(float(data.get("likelihood", 0))))
    except (TypeError, ValueError):
        likelihood = 0
    likelihood = max(0, min(100, likelihood))
    reasoning = str(data.get("reasoning") or "").strip()
    return {"likelihood": likelihood, "band": _band(likelihood),
            "reasoning": reasoning, "source": "gemini"}


def run_ai_detection(text: str) -> Dict[str, Any]:
    """Prefer the Copyleaks AI Detector (accurate) when configured; otherwise fall back to the
    free Gemini heuristic. Any Copyleaks error (no key, hiccup, too-short text) falls back too,
    so the check never breaks."""
    try:
        import copyleaks_client
        if copyleaks_client.available():
            return copyleaks_client.ai_detection(text)
    except Exception:
        pass
    return _gemini_ai_detection(text)
